### ISSUE TITLE
Question: do processes automatically stop when done?

### ISSUE THREAD

**Issue by Integralist** [alex-sherman/deco#1]
Hi,

This looks like a great tool :-)

Just wondering about the memory performance of potentially spinning up lots of processes. 

Also, once a set of processes are spun up to handle the users parallel requirements, do they get destroyed? is thatpossible or does that not make sense to do?

Hopefully you can help me understand the answer to these questions. 

Thanks!

**Comment by alex-sherman** [comment]
That's a good question, I should probably clarify this in the readme somewhere.

Almost all of the performance stuff is handled by multiprocessing.pool, which is a great library. The processes that pool spins up require very little memory on their own, but if a lot of data is being passed to the concurrent function there's a potential for a lot of memory being used to copy the function arguments into each process's address space. This is sort of a general problem in parallel programming with Python. Because we're forced to use separate processes, any required data needs to be copied around to all of them.

However these processes do get periodically destroyed, specifically after every synchronization event. This means if you use `@synchronized`, the processes are guaranteed to be closed before you leave the decorated function. Otherwise they get closed after each call to wait().

**Comment by Integralist** [comment]
Thanks. Appreciate you taking the time to get back to me. That makes sense. I look forward to playing around with this module :-)
