### ISSUE TITLE
NameError: name 'concurrent' is not defined

### ISSUE THREAD

**Issue by nafizh** [alex-sherman/deco#15]
This was my program. 

```python
@concurrent
def add_to_list(num):
    num = num + 1
    return num

x = []
@synchronized
def loop_to_add():
    for i in xrange(1, 100000):
        x.append(add_to_list(i))
    return x

loop_to_add()
print "Done"
```
It shows the error -

>---------------------------------------------------------------------------
NameError                            Traceback (most recent call last)
 \<ipython-input-73-6f1a457862c5\> in \<module\>()
      1 #%%timeit
----> 2 @concurrent
      3 def add_to_list(num):
      4     num = num + 1
      5     return num
NameError: name 'concurrent' is not defined

I think I am doing something silly here. But I cannot seem to figure out what.

**Comment by alex-sherman** [comment]
Did you remember to `from deco import *`?

Additionally the line for `x.append(add_to_list(i))` is not allowed within an `@synchronized` function. Currently I think no exceptions are raised (which would be a great improvement) but this program will not work the way you expect.

`@synchronized` functions only support assignment of `@concurrent` function results to index-able objects. So a rewrite might look like:

```python
x = [None] * 100000
@synchronized
def loop_to_add():
    for i in xrange(1, 100000):
        x[i] = add_to_list(i)
    return x
```

I'll have to consider supporting other uses of the return value of `@concurrent` functions like this, at the very least the user should be warned that this will not produce the expected behavior.

**Comment by nafizh** [comment]
Yeah, I did not do that. Actually when I tried to type `from deco import *`, after typing `from de`, if I press tab in ipython, it was not showing `deco`. After I saw your reply, I just typed the whole line and now it works.

I do not really know much about how parallelism works. Can you please explain why if I run the same code without using `deco` it takes less time?

```python
from deco import *

import time
start_time = time.time()

@concurrent
def add_to_list(num):
    num = num + 1
    return num

x = [None] * 100000
@synchronized
def loop_to_add():
    for i in xrange(1, 100000):
        x[i] = add_to_list(i)
    return x

loop_to_add()
print("--- %s seconds ---" % (time.time() - start_time))
print "Done"
#timeit foo()
```
Output:
>--- 6.46950006485 seconds ---
Done

On the other hand-
```python
#from deco import *

import time
start_time = time.time()

#@concurrent
def add_to_list(num):
    num = num + 1
    return num

x = [None] * 100000
#@synchronized
def loop_to_add():
    for i in xrange(1, 100000):
        x[i] = add_to_list(i)
    return x

loop_to_add()
print("--- %s seconds ---" % (time.time() - start_time))
print "Done"
#timeit foo()
```

Output:
>--- 0.0946800708771 seconds ---
Done

**Comment by alex-sherman** [comment]
This is actually a great observation that should be made a little more clear in the readme/documentation.

Functions that take little to no time to return are not great candidates for parallelization with this method. The reason is that marking a function with `@concurrent` incurs a little bit of overhead each time you call the function (in this case ~60 microseconds). Because add_to_list takes way less time (~100 nano seconds), most of the execution time comes from the overhead!

As a good rule of thumb, only `@cuncurrent` functions that take longer than ~1ms to complete will get a performance increase.

Hope that makes sense and I'll try to include this in the readme somewhere. Thanks for bringing it up!
