### ISSUE TITLE
Support pluggable pool classes

### ISSUE THREAD

**Issue by njatkinson** [alex-sherman/deco#20]
As a deco user, I would like to be able to specify the type of pool to be used for concurrent work so that I can use the concurrency model (threads, processes, etc.) most suited to my workload.

For example, if I'm doing network IO bound work, I may want to use the multiprocessing.pool.ThreadPool rather than multiprocessing.Pool in order to avoid the overhead of creating new Python processes. I may want to add some features to Pool, say auditing & profiling, so I've created a subclass of Pool to add the features, and I would like to use it with deco.

The change would be to add a supported argument to `concurrent` decorator-- something like `concurrent(pool_class = SomeClass)`. It appears that this will only require a change to the `__init__` method of `concurrent` in order to check for the presence of this argument and set the instance local pool class, and a single line change to `__call__`-- `if self.pool is None: self.pool = self.pool_class(....)`.

Does this sound reasonable to you all?

**Comment by alex-sherman** [comment]
Yeah we're definitely interested in support more varieties of concurrent backends. ThreadPool would be a great one, and we were also hoping to add support for Apache's libcloud to allow distributed computing. I think we're going to take some time to design a good abstraction for this, so that all of these backends can behave the same way and remain simple. I'm going to leave this open and follow up when we have a better idea of how to support these options.

Additionally if anyone else has some input on this please feel free to respond!

**Comment by alex-sherman** [comment]
I've added some really basic support for this with b347a27a7274357362c6f60d507e9757957d2a00. If you take a look at [examples/threads.py](https://github.com/alex-sherman/deco/blob/master/examples/threads.py) it shows the simple usage with `ThreadPool`. I'll have to start working on some proper documentation, but I hope this is enough for now.

Thanks again for the input!
