### ISSUE TITLE
Assignment attempted on something that is not index based

### ISSUE THREAD

**Issue by aliabbasjp** [alex-sherman/deco#24]
I am using a dictionary to store the contents of two files to enable parallel loading of both file in a dictionary, yet I get an error:

```

@concurrent
def readfile(path):
    return codecs.open(path, encoding='utf-8').read()


@synchronized
def readdocs():
    d=dict()
    d['source']=readfile(r'./../accessmysql/t1')
    d['target']=readfile(r'./../accessmysql/t2')
    return d
if __name__ == '__main__':
    d=readdocs()
   
```

Giver error:
ValueError: Assignment attempted on something that is not index based

**Comment by aliabbasjp** [comment]
This works
```
@synchronized
def readdocs(*docs):

    d=dict()
    for el in docs:
        d[el]=readfile(el)


    return d
```

**Comment by alex-sherman** [comment]
I believe this should have been fixed in 79fe24c9b5f0c30d1ea2db4ce418ed20a00a3385. If you're installing from PyPi/pip I apologize for not creating a new release yet with these improvements.

If you can, try cloning the repo or doing a pull if you have cloned it already, and then running `python setup.py install` from there.

Otherwise I should be able to do a new release soon as well for pip, I'm just trying to nail down one or two more things. Sorry it's taking so long!

**Comment by aliabbasjp** [comment]
@alex-sherman  that breaks the ipython and gives this error:

http://stackoverflow.com/questions/34413779/ipython-nameerror-name-pkg-resources-is-not-defined

**Comment by alex-sherman** [comment]
You could try the solutions posted on that stackoverflow post, it seems to be related to IPython and file privileges which aren't really something I can debug with you. If you can't get the `setup.py` to work, I did manage to push a new version of deco to PyPi so you could also try installing it again with `pip install deco --upgrade`.

Anyway I'm going to close this for now since it is fixed in the latest version, but do let me know if the newest version still doesn't work though for whatever reason. Thanks for posting this!
