### ISSUE TITLE
thread/process count

### ISSUE THREAD

**Issue by rhaarm** [alex-sherman/deco#32]
I just wanted to verify this, since it doesn't seem to be documented.

In conc_test.py I see the use of _**test.processes**_, does this set the max thread/process count for that specific concurrent function? What does the _**test.p = None**_ refer too?

**Comment by alex-sherman** [comment]
That is from an older version deco, those two attributes have since gone away. I hope to create some documentation in the future, but for now here's how you would recreate that functionality.

**Setting the number of processes**
The number of processes/threads can be configured through the `@concurrent` constructor like so:
```python
@concurrent(processes = 5)
def test():
    pass
````
In general, whatever you pass in to the constructor gets passed directly to the `Pool `or `ThreadPool `constructor which is [documented more here](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool).

**Changing the process count**
The first time the concurrent function gets called a `Pool `or `ThreadPool `is created, so the process count is sort of finalized. The previous call to `test.p = None` was sort of a cheat to get the concurrent function to re-construct the pool. A way to do it now would be:
```python
test.conc_kwargs["processes"] = 5
test.concurrency = None
```
Changing the process count after the concurrent function has been initialized is kind of expensive and not something I really thought of much, so this second functionality might later get wrapped up in a cleaner way.

Thanks for asking this question, let me know if something still isn't clear.

**Comment by rhaarm** [comment]
Thanks, this was extremely helpful information.
