### ISSUE TITLE
generator argument

### ISSUE THREAD

**Issue by rhaarm** [alex-sherman/deco#35]
I'm doing some heavy work on csv and would like to pass a ```generator``` into the ```@concurrent``` function, but script just stalls, so when I swap it out for a ```list```, it actually runs.

**Comment by alex-sherman** [comment]
Accessing generators inside the concurrent function should be avoided. I'm not exactly sure what's going on to cause it to hang, but generators are definitely not process safe by default and deco can't synchronize them because they're not index based mutations. If you can avoid passing the entire generator into the concurrent function, and rather iterate over the generator in the `@synchronized` function to pass the value to operate on into the `@concurrent` function things should work fine.

I added a short [pitfalls page](https://github.com/alex-sherman/deco/wiki/Common-Pitfalls) to the wiki that mentions this and hopefully clarifies some of the limitations of deco functions.
