### ISSUE TITLE
cannot import concurrent

### ISSUE THREAD

**Issue by zlan1** [alex-sherman/deco#47]
from PIL import Image
from deco import concurrent, synchronized
import time

@concurrent
def slow(index):
    time.sleep(5)

@synchronized
def run():
    for index in list('123'):
        slow(index)

run()

When I ran the code above, I get error msg below:
"C:\Program Files\Anaconda3\python.exe" C:/Users/zlan1/PycharmProjects/hellow/parallel_computing/deco.py
Traceback (most recent call last):
  File "C:/Users/zlan1/PycharmProjects/hellow/parallel_computing/deco.py", line 2, in <module>
    from deco import concurrent, synchronized
  File "C:\Users\zlan1\PycharmProjects\hellow\parallel_computing\deco.py", line 2, in <module>
    from deco import concurrent, synchronized
ImportError: cannot import name 'concurrent'

Process finished with exit code 1

**Comment by alex-sherman** [comment]
It has to do with the name of your local script also being `deco.py`. If you rename it to something else, everything should work.

Python's import will get confused by it since it tries to import from the local directory before looking at libraries, so it's trying to import `concurrent` out of your own script.
